# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee53061f490bbd6c09a7093fe8f3a2e2c197d729a10f09ba006143feb0297a0b1cf0f0995091ac177946036030db5d05004c33a08ca2441f89f63ba43a832e6c

test:
  secret_key_base: ebd99d5f4e50f2475e0dd013f0e20e57e35cebdc08c3427e58930d5a8af15f03adbc4127e92702a866daccd7f17bf4f72b189db2ef3b0481db6f8c03e41b3f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
